# Generated by Django 5.0.3 on 2024-05-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='admin_role',
            field=models.CharField(choices=[('Superadmin', 'superadmin'), ('Admin', 'admin')], default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
